version: "3.7"
services:
  postgresql:
    build: /Users/kameshs/git/rhdemo/openshift-pgsql12-primary-centos7
    ports:
      - "5432:5432"
    environment:
      PG_USER_PASSWORD: password!
      PG_USER_NAME: demo
      PG_DATABASE: gamedb
      PG_NETWORK_MASK: all
      PG_MAX_CONNECTIONS: 100
      PG_SHARED_BUFFERS: 256
      PG_WORK_MEM: 1536
      PG_EFFECTIVE_CACHE_SIZE: 1
      PG_EFFECTIVE_IO: 128
      PG_MAX_WAL_SIZE: 1
    volumes:
      - type: bind
        source: /Users/kameshs/git/rhdemo/openshift-pgsql12-primary-centos7/pgdata
        target: /pgdata
  client:
    build: ./
    depends_on: ["postgresql"]
    environment:
      PG_USER_PASSWORD: password!
      PG_USER_NAME: demo
      PG_DATABASE: gamedb
      PG_HOST: postgresql
    ports:
      - "8080:8080"
    volumes:
      - type: bind
        source: /Users/kameshs/git/rhdemo/openshift-pgsql12-primary-centos7/pgdata
        target: /pgdata
