version: "3.1"
services:
  postgresql:
    image: quay.io/redhatdemo/openshift-pgsql12-primary:centos7
    ports:
      - "5432:5432"
    environment:
      PG_USER_PASSWORD: password!
      PG_USER_NAME: demo
      PG_DATABASE: gamedb
      PG_NETWORK_MASK: all
  pgclient:
    build: ./
    depends_on: ["postgresql"]
    environment:
      PG_USER_PASSWORD: password!
      PG_USER_NAME: demo
      PG_DATABASE: gamedb
      PG_HOST: postgresql
      PG_PORT: 5432
    command: ["-c", "SELECT now()"]
